## Практическая работа

В этой практической работе пять обязательных задач.

*Обязательные задачи* помогут проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении модели линейной регрессии.
2.   Потренироваться в обучении модели логистической регрессии. 
3.   Потренироваться в обучении модели многослойного персептрона.





Что оценивается:

*   Все пункты и критерии приёмки по каждому заданию выполнены.
*   Код оформлен и работает корректно.





Как отправить работу на проверку:

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

В этом задании вам нужно построить модель классификации, определяющую категорию цены/цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Мы будем использовать датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.


### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

## Обязательные задачи

In [1]:
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier

In [2]:
df = pd.read_csv('data/vehicles_dataset_prepared.csv')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

**Задача 0. Линейная регрессия**

Вспомните задачу по предсказанию стоимости поддержанного автомобиля. Попробуем обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого проделайте следующие шаги:

- Подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`).
- Разделите выборку на треин и тест в отношении 70/30.
- Обучите модель линейной регрессии с дефолтными параметрами.
- Посчитайте значение метрики mae на тестовой выборке для линейной регрессии.
- Выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_`. Есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом
- Удалите фичи, коэффициенты которых равны нулю. И переобучите модель. Убедитесь, что значение метрики не изменилось.



In [3]:
# Ваш код здесь
df_copy = df.copy()

x = df_copy.drop(['odometer/price_std', 'price_category', 'price'], axis = 1)
y = df_copy.price

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [4]:
lr = LinearRegression()

In [5]:
lr.fit(x_train, y_train)

LinearRegression()

In [6]:
pred_train = lr.predict(x_train)
pred_train

array([30274.20830505, 35813.54920435, 30082.37549297, ...,
       13902.56660667, 31782.46237165, 13543.99477083])

In [7]:
pred_test = lr.predict(x_test)
pred_test

array([17157.33358779, 16079.47317044, -3412.37232896, ...,
        6486.80758013, 24803.52793774,  6771.9965711 ])

In [8]:
mean_absolute_error(y_test, pred_test)

4600.341121384864

In [9]:
lr.coef_

array([ 6.35951029e-06,  2.54303045e+02,  1.07390957e+03, ...,
       -1.66691605e+02,  2.30504369e+01, -2.80397708e+03])

In [10]:
coef_list = list(zip(x_train.columns, lr.coef_))
coef_list.sort(key = lambda x: x[1], reverse = True)
coef_list

[('short_model_Peterbilt', 57474.827892016176),
 ('short_model_PLYMOUTH', 48653.753711829275),
 ('short_model_belair', 43264.1572552326),
 ('short_model_1966', 41204.78807214696),
 ('short_model_eurovan', 36080.47039383625),
 ('short_model_tudor', 35620.67827119835),
 ('short_model_Chevorlet', 34627.88369820346),
 ('short_model_Lotus', 33427.02632978321),
 ('short_model_defender', 33172.110765584315),
 ('short_model_chevelle', 31178.354166981822),
 ('short_model_tc5500', 28543.152022956332),
 ('short_model_gt-r', 28081.11623942741),
 ('short_model_e46', 27577.76008273648),
 ('short_model_D7FH173552', 26818.677510676156),
 ('short_model_325is', 26479.159870126572),
 ('short_model_c-10', 24226.678447424423),
 ('short_model_v6', 24101.920470685916),
 ('short_model_2017', 23933.048465677603),
 ('short_model_autobiography', 23134.724434311946),
 ('short_model_1968', 22801.394084702468),
 ('short_model_4-runner', 21633.00127273252),
 ('short_model_lemans', 21593.05825096359),
 ('short_model_

In [11]:
l1 = []
for i in coef_list:
    if i[1] == 0:
        l1.append(i[0]) 
l1

['manufacturer_ferrari']

In [12]:
x_train.drop(columns = l1, axis = 1, inplace = True)
x_test.drop(columns = l1, axis = 1, inplace = True)
x_train.head()

id  is_audi  is_ford  is_chevrolet  is_toyota  x0_diesel  \
3781  7314842398        0        0             0          0        0.0   
6101  7316005173        0        0             1          0        0.0   
491   7316501929        0        0             0          0        0.0   
3017  7307760453        0        0             0          0        0.0   
3872  7314536873        0        0             0          0        0.0   

      x0_electric  x0_gas  x0_hybrid  x0_other  ...   lat_std  long_std  \
3781          0.0     1.0        0.0       0.0  ...  4.014776 -3.105861   
6101          0.0     1.0        0.0       0.0  ... -0.107626 -1.581399   
491           0.0     1.0        0.0       0.0  ...  0.639417  1.237475   
3017          0.0     1.0        0.0       0.0  ...  1.502791 -1.591485   
3872          0.0     1.0        0.0       0.0  ... -0.816561  0.714005   

      year_std  desc_len_std  model_in_desc_std  model_len_std  \
3781  1.165789      0.342749          -0.155788      -0.453583   
6101 -2.592738     -0.695912          -0.155788      -0.453583   
491   0.382762      0.582944          -0.155788       1.393977   
3017  1.165789      1.583392          -0.155788      -1.146418   
3872 -2.592738     -0.980871           0.265739      -0.915473   

      model_word_count_std  month_std  dayofweek_std  diff_years_std  
3781             -0.788810  -0.615846       0.621233       -1.165789  
6101             -0.788810   1.623784      -1.374972        2.592738  
491               1.910669   1.623784      -1.374972       -0.382762  
3017             -0.788810  -0.615846       0.621233       -1.165789  
3872             -0.788810  -0.615846       0.122182        2.592738  

[5 rows x 1459 columns]

In [13]:
lr.fit(x_train, y_train)

LinearRegression()

In [14]:
pred_train = lr.predict(x_train)
pred_train

array([30274.20830532, 35813.5492046 , 30082.37549253, ...,
       13902.56660762, 31782.46237108, 13543.99477122])

In [15]:
pred_test = lr.predict(x_test)
pred_test

array([17157.33358857, 16079.47316862, -3412.37232966, ...,
        6486.80757897, 24803.52793814,  6771.99660756])

In [16]:
mean_absolute_error(y_test, pred_test)

4600.341119869057

**Задача 1. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели нужно:

- рассчитать и вывести метрику качества (accuracy) на тренировочной выборке;
- сделать предикт на тестовых данных и положить его в переменную `logreg_pred`;
- рассчитать и вывести accuracy и confusion_matrix на тестовой выборке.


Задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные, тюнить параметры логистической регрессии.

In [17]:
# Ваш код подготовки данных здесь. Допишите инициализацию входных фичей и целевую переменную
#Очень долго не мог понять, почему точность предсказания была чуть выше 32%. Далее почитав чат, понял, что нужно удалить
#колонку 'id'. После этого всё стало на свои места
x = df_copy.drop(['odometer/price_std', 'price_category', 'price', 'id'], axis = 1)
y = df_copy.price_category

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [18]:
# Ваш код обучения моделей здесь

log_reg = LogisticRegression(C = 5, penalty = 'l2', solver = 'newton-cg')
log_reg.fit(x_train, y_train)

LogisticRegression(C=5, solver='newton-cg')

In [19]:
#Делаю предсказания на тестовой выборке
logreg_pred = log_reg.predict(x_test)
logreg_pred

array(['high', 'medium', 'low', ..., 'low', 'medium', 'low'], dtype=object)

In [20]:
print('Точность предсказания по метрике accuracy на тестовой выборке:', accuracy_score(y_test, logreg_pred))

Точность предсказания по метрике accuracy на тестовой выборке: 0.7605682605682605


In [21]:
confusion_matrix(y_test, logreg_pred)

array([[803,  24, 170],
       [ 24, 769, 160],
       [150, 163, 623]], dtype=int64)

In [22]:
#Проверяю предсказания на тренировочной выборке
logreg_pr = log_reg.predict(x_train)
print('Точность предсказания по метрике accuracy на тренировочой выборке:', accuracy_score(y_train, logreg_pr))

Точность предсказания по метрике accuracy на тренировочой выборке: 0.8857864250705481


In [23]:
confusion_matrix(y_train, logreg_pr)

array([[2025,   25,  152],
       [  38, 2020,  189],
       [ 133,  232, 1919]], dtype=int64)

**Задача 2. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. Добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии, с помощью данного алгоритма. 

Значимым увеличением точности в данном задании будем считать увеличение больше, чем на 0.01 по метрике accuracy.

In [24]:
# Ваш код здесь
mlp = MLPClassifier(random_state = 42, max_iter = 500, activation = 'tanh', hidden_layer_sizes = (100, 20))

In [25]:
mlp.fit(x_train, y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=(100, 20), max_iter=500,
              random_state=42)

In [26]:
pred_mlp_train = mlp.predict(x_train)
accuracy_score(y_train, pred_mlp_train)

1.0

In [27]:
pred_mlp_test = mlp.predict(x_test)
print(pred_mlp_test)
print(accuracy_score(y_test, pred_mlp_test))

['high' 'medium' 'low' ... 'low' 'medium' 'low']
0.7761607761607762


**Задача 3. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, и обоснуйте свой выбор.

In [28]:
# Ваш код здесь
from sklearn.ensemble import RandomForestClassifier

In [29]:
rf_clf = RandomForestClassifier()
rf_clf.fit(x_train, y_train)

RandomForestClassifier()

In [30]:
pred_rf_train = rf_clf.predict(x_train)
pred_rf_test = rf_clf.predict(x_test)

print(pred_rf_test)
print(accuracy_score(y_train, pred_rf_train))
print(accuracy_score(y_test, pred_rf_test))

['high' 'medium' 'low' ... 'low' 'medium' 'low']
1.0
0.7602217602217602


# Ответ на вопрос
Сравнивая результаты предсказания по трем моделям можно сделать вывод, что наилучшей предсказательной способностью обладает модель на основе нейронных сетей, т.к. её точность по метрике accuracy для тестовой выборки является самой высокой. Также неплохой результат показала модель на основе случайного леса, т.к. её предсказательная способность на тренировочной выборки является такой же хорошей, как для нейронной сети. Я хотел бы также отметить тот факт, что для случайного леса в задании не стояло никаких ограничений по полученным значениям метрики accuracy, поэтому, возможно, что точность получаемая при помощи случайного леса может иметь более высокую точность, чем модель логистической регрессии. Возможно перебирая настраиваемые параметры случайного леса можно получить более высокую точность.
Также стоит отметить, что модель на случайном лесе показала наилучший результат при дефолтных параметрах, чем две другие модели. С двумя оставшимися моделями для получения достигнутого результата пришлось подбирать и весьма не мало по времени настраиваемые параметры моделирования.

**Задача 4. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвертую колонку `target` положите тот класс, который предсказало большинство классификаторов. Например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`.

     Если в строке три разных класса — `high, medium, low`, — придумайте свою стратегию по выбору значения. Самая простая стратегия: выбрать рандомно одно значение из трёх.

- посчитайте точность предсказания с помощью голосования. Выведите значения метрик accuracy и confusion_matrix.


Добейтесь значения точности > 78% 

In [31]:
# Ваш код здесь
import numpy as np
pred_df = pd.DataFrame(
    {'Logistic': pred_rf_test,
     'Neural': logreg_pred,
     'RandomTree': pred_mlp_test
    })
pred_df


Logistic  Neural RandomTree
0        high    high       high
1      medium  medium     medium
2         low     low        low
3         low     low        low
4        high    high       high
...       ...     ...        ...
2881   medium  medium     medium
2882      low     low     medium
2883      low     low        low
2884   medium  medium     medium
2885      low     low        low

[2886 rows x 3 columns]

In [32]:
import random
pred_df['target'] = pred_df.apply(lambda x: x.mode()[0], axis = 1)
pred_df.head()

Logistic  Neural RandomTree  target
0     high    high       high    high
1   medium  medium     medium  medium
2      low     low        low     low
3      low     low        low     low
4     high    high       high    high

In [33]:
accuracy_score(y_test, pred_df.target)

0.7834372834372835

In [34]:
confusion_matrix(y_test, pred_df.target)

array([[829,  22, 146],
       [ 24, 797, 132],
       [146, 155, 635]], dtype=int64)

**Примечание:**

В этом домашнем задании в задаче номер 1 и далее перед вами встал выбор: включать ли в обучение колонку `id`. При удалении данной колонки во время обучении логистической регрессии качество заметно улучшается.

Вообще обучать любую модель (будь то логистическая или линейная регрессия, или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь "заточить" результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе "частных случаев", и, возможно, не обратит внимание на общие зависимости.   